version: "2.1"

services:
  db:
    image: postgres:latest
    expose:
      - 5432

  redirect:
    image: geldim/https-redirect
    ports:
      - 80:80

  web:
    build: .
    env_file: .env
    image: assemble/web
    command: ./bin/serve
    ports:
      - "$PORT:3000"
    links:
      - db
    volumes:
      - .:/app
      # Docker access on Linux
      - /var/run/docker.sock:/var/run/docker.sock

  worker:
    env_file: .env
    image: assemble/web
    command: rake jobs:work
    links:
      - db
    volumes:
      - .:/app
      # Docker access on Linux
      - /var/run/docker.sock:/var/run/docker.sock
